spring:
  ai:
    mcp:
      server:
        name: image-search-mcp-server
        version: 0.0.1
        type: SYNC
        stdio: true
  #?? web
  main:
    web-application-type: none
    banner-mode: off