spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  ai:
    dashscope:
      api-key: ${spring.ai.dashscope.api-key}
      chat:
        options:
          model: qwen-plus
search-api:
  api-key: ${search-api.api-key}

langsearch:
  api-key: ${langsearch.api-key}

pexels:
  api-key: ${pexels.api-key}

oss:
  aliyun:
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    region: "cn-hangzhou"
    bucketName: "code-aiagent"