spring:
  application:
    name: ai-agent
  profiles:
    active: local
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    mcp:
      client:
        # MCP 客户端超时配置
        timeout: 30000  # 30秒超时
        connection-timeout: 10000  # 连接超时10秒
        read-timeout: 20000  # 读取超时20秒
        sse:
          connections:
            server1:
              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yt.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8123
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            condition: ERROR


